### ISSUE TITLE
Error in console 

### ISSUE THREAD

**Issue by YohSambre** [NubTheFatMan/nadmin#1]
Greetings, I tried to install your system but I did not succeed, it is well in the addons folder of my ftp but when I try to open the panel nothing happens and my consoler is bombarded with errors

[https://pastebin.com/HNvLrFHx](url)

**Comment by NubTheFatMan** [comment]
What did you do on the server? Looking at the line that created the error, you or another player had to have tried running a command. That section of code should only be running when the server receives a command from a player

**Comment by YohSambre** [comment]
I just try to open the menu with the nadmin command in dev console

**Comment by NubTheFatMan** [comment]
Oh, I see. Just "nadmin"? I don't have any auto-completion, and I don't check if the command is empty. Try running "nadmin menu" or "!menu" in chat. Let me know if that works for you

**Comment by YohSambre** [comment]
seems to work but how the hell do you set a superadmin player?

**Comment by NubTheFatMan** [comment]
That's my fault. I haven't properly documented how to use it yet since I have yet to actually complete it. I haven't worked on it for a minute. It works, it's mostly missing configuration stuff at this point. Anyway, you can do `nadmin rank [your_name] owner` or `nadmin rank [your_steam_id] owner`. If you're name has a space, then just do part of your name. As an example, if I did `nadmin rank nub owner`, I would be set as owner, even with my name "NubTheFatMan".
